### ISSUE TITLE
[Bug] Website Crash During Map Layers Load

### ISSUE THREAD

**Issue by igorho2000** [tpe-doit/Taipei-City-Dashboard-FE#20]
> Please submit all issues in English.

## Describe the bug

For larger map layers, if the user closes the toggle before the map has finished loading and then toggles the map again, the site may crash.

## To Reproduce

1. Click on toggle to open map (for 城市屋齡分佈、路燈分佈)
2. Close the toggle before the map loads
3. Open the map again

## Expected behavior

The loading of a map layer should be paused if the toggle is closed.

## Screenshots

N/A

## Environment Info

-   Device: PC
-   OS: Windows
-   Browser: Chrome

## Additional context

N/A

(Fill in "x" to check)

-   [x] I would like to work on this issue myself if approved.

**Comment by tpe-doit** [comment]
Resolved by pull request #21
