### ISSUE TITLE
[Enhancement] Add Arc Map Type

### ISSUE THREAD

**Issue by igorho2000** [tpe-doit/Taipei-City-Dashboard-FE#22]
> Please submit all issues in English.

## Type

-   [ ] Application Functionalities
-   [ ] New Chart Type
-   [x] New Map Type
-   [ ] Other

## Please describe your feature request

In addition to 2D lines, 3D arcs may provide a clearer representation of paths that intersect. This map type would support lines with only two points and render curves of varying heights and curvatures based on distance. A new package, "Threebox" needs to be added to render the curves. An example is shown below.

## Describe alternatives you've considered

N/A

## Additional context

![Screenshot 2023-09-27 at 1 40 05 PM](https://github.com/tpe-doit/Taipei-City-Dashboard-FE/assets/105908220/4000471d-a134-4284-a557-9309919a8516)

(Fill in "x" to check)

-   [x] I would like to work on this issue myself if approved.

**Comment by tpe-doit** [comment]
Looks good!

use "arc" as the map type name.
