### ISSUE TITLE
[Enhancement] Add HeatMapChart

### ISSUE THREAD

**Issue by igorho2000** [tpe-doit/Taipei-City-Dashboard-FE#24]
> Please submit all issues in English.

## Type

-   [ ] Application Functionalities
-   [x] New Chart Type
-   [ ] New Map Type
-   [ ] Other

## Please describe your feature request

Add the heatmap chart type which will support the 3D data type. Will use Apexchart's existing module.

## Describe alternatives you've considered

N/A

## Additional context

![Screenshot 2023-09-28 at 4 25 29 PM](https://github.com/tpe-doit/Taipei-City-Dashboard-FE/assets/105908220/377a8ac7-c14c-4cdd-930c-f3a38a359e90)

(Fill in "x" to check)

-   [x] I would like to work on this issue myself if approved.

**Comment by tpe-doit** [comment]
Looks interesting! Approved!
