### ISSUE TITLE
[Bug] Poor Mapbox Performance On Mobile

### ISSUE THREAD

**Issue by igorho2000** [tpe-doit/Taipei-City-Dashboard-FE#47]
> Please submit all issues in English.

## Describe the bug

When maps are rendered on mobile, oftentimes the application will run out of memory. This is probably due to our rendering most maps locally via geojsons as this is a static application.

In the internal version, most maps are rendered first on the server (geoserver) and served to the application as raster maps. This greatly improves the performance of Mapbox.

As Taipei City Dashboard 2.0 completes the open-source of its backend and database, this problem should go away as we will transition back to using raster maps.

**However, we would still like to improve the performance of locally rendered maps and would welcome any community contribution on this matter.**

## To Reproduce

1. Go to maps on mobile
2. Open a slightly larger map
3. Blank screen (oom)

> Issues without reproduction steps or code examples may be immediately closed as not actionable.

## Expected behavior

Maps to be rendered properly.

## Screenshots

N/A

## Environment Info

-   Device: iPhones are known to have this issue. Android phones fare better. PCs are all fine to my knowledge.
-   OS: iOS
-   Browser: chrome, safari

## Additional context

Geojsons are currently rendered as per the Mapbox docs. We are also in the process of cleaning existing geojsons. Contributions to this issue can attempt to streamline the map rendering process and see if that helps.

**Contestants of Taipei Codefest 2023 do not have to worry about this issue as all demonstrations will be conducted via PC.**

(Fill in "x" to check)

-   [ ] I would like to work on this issue myself if approved.

**Comment by tpe-doit** [comment]
Removed maps temporarily in the new mobile version.
